# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5224af7a8b678ea08a68be9a9501c79b3ebc5c493cc22f7b677b57ac256a55a85527a6fdc69efae48231fac41609118a6a06673b11cf05bead035b8b80c50162

test:
  secret_key_base: 76aa4b9ffda2334eb74747b34a893fd120e97e8d95273b0c08f6e836696c7255b8839b2537452bd745f21469b8a256808edfa0d0e37dac049823c5cc03d7dc51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
